version: '3.8'  # Define a versão do arquivo de configuração do Docker Compose. A versão 3.8 é amplamente compatível e atual.

services:  # Início da seção que define os serviços a serem criados pelo Docker Compose.
  oracle-db:  # Nome do serviço. Você pode chamar de qualquer nome que preferir.
    image: gvenzl/oracle-xe:21-slim  # Especifica a imagem Docker a ser usada. Aqui, utilizamos uma imagem Oracle XE 21c slim.
    container_name: oracle-21c-xe  # Nome do contêiner. É o nome amigável que você verá quando listar os contêineres em execução.
    
    ports:
      - "1521:1521"  # Mapeia a porta 1521 do contêiner para a porta 1521 no host. Essa é a porta padrão para conexões SQL.
      - "5500:5500"  # Mapeia a porta 5500 do contêiner para a porta 5500 no host. Esta porta é usada para o Oracle Enterprise Manager.

    environment:  # Definição das variáveis de ambiente para configurar o Oracle.
      - ORACLE_PASSWORD=123S.E.N.H.A.321  # Define a senha para o usuário SYS e SYSTEM. Altere para uma senha segura.
      - ORACLE_MEM=2GB  # Define a quantidade de memória que o Oracle pode usar. Aqui estamos definindo 2GB, mas você pode ajustar conforme necessário.
      - ORACLE_PDB=XEPDB1  # Nome do Pluggable Database (PDB). O padrão é XEPDB1, mas você pode alterar conforme suas necessidades.
      - ORACLE_SID=XE  # Define o SID (System Identifier) do banco de dados. O SID padrão para Oracle XE é 'XE'.
    
    volumes:
      - oracle_data:/opt/oracle/oradata  # Mapeia um volume persistente para armazenar os dados do banco. Isso garante que os dados persistam mesmo se o contêiner for removido.

    healthcheck:  # Define uma verificação de integridade para monitorar se o banco de dados está ativo e funcionando.
      test: ["CMD-SHELL", "echo 'select 1 from dual;' | sqlplus sys/123S.E.N.H.A.321@//localhost:1521/XE as sysdba"]
      # O comando acima tenta executar uma consulta simples no banco de dados. Se a consulta retornar 1, o banco está funcionando corretamente.
      interval: 1m30s  # Define o intervalo entre as verificações de integridade (a cada 1 minuto e 30 segundos).
      timeout: 30s  # Define o tempo máximo que uma verificação pode demorar antes de ser considerada como falha.
      retries: 3  # Número de tentativas antes de considerar que o serviço está indisponível.

volumes:  # Define volumes que serão usados para persistir os dados.
  oracle_data:  # Nome do volume. Esse volume armazenará os dados do Oracle para que não sejam perdidos se o contêiner for removido.


# docker-compose up -d 
# docker-compose up --build -d


# docker-compose down